

services:
  service_a:
    build: ./serviceA
    ports:
      - "3000:3000"
      - "3001:3001"
    depends_on:
      - sqldb
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=example
      - DB_NAME=testdb
    volumes:
      - ./serviceA:/app
      - ./serviceB:/app/serviceB
      
  service_b:
    build: ./serviceB
    ports:
      - "5000:5000"
      - "5001:5001"
    volumes:
      - ./serviceB:/app
  
  sqldb:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: testdb  