// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.1
// source: getrates_req.proto

package protomodel

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GetRatesService_GetRates_FullMethodName = "/protomodel.GetRatesService/GetRates"
)

// GetRatesServiceClient is the client API for GetRatesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GetRatesServiceClient interface {
	GetRates(ctx context.Context, in *RatesRequest, opts ...grpc.CallOption) (*RatesResponse, error)
}

type getRatesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGetRatesServiceClient(cc grpc.ClientConnInterface) GetRatesServiceClient {
	return &getRatesServiceClient{cc}
}

func (c *getRatesServiceClient) GetRates(ctx context.Context, in *RatesRequest, opts ...grpc.CallOption) (*RatesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RatesResponse)
	err := c.cc.Invoke(ctx, GetRatesService_GetRates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetRatesServiceServer is the server API for GetRatesService service.
// All implementations must embed UnimplementedGetRatesServiceServer
// for forward compatibility.
type GetRatesServiceServer interface {
	GetRates(context.Context, *RatesRequest) (*RatesResponse, error)
	mustEmbedUnimplementedGetRatesServiceServer()
}

// UnimplementedGetRatesServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGetRatesServiceServer struct{}

func (UnimplementedGetRatesServiceServer) GetRates(context.Context, *RatesRequest) (*RatesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRates not implemented")
}
func (UnimplementedGetRatesServiceServer) mustEmbedUnimplementedGetRatesServiceServer() {}
func (UnimplementedGetRatesServiceServer) testEmbeddedByValue()                         {}

// UnsafeGetRatesServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GetRatesServiceServer will
// result in compilation errors.
type UnsafeGetRatesServiceServer interface {
	mustEmbedUnimplementedGetRatesServiceServer()
}

func RegisterGetRatesServiceServer(s grpc.ServiceRegistrar, srv GetRatesServiceServer) {
	// If the following call pancis, it indicates UnimplementedGetRatesServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GetRatesService_ServiceDesc, srv)
}

func _GetRatesService_GetRates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GetRatesServiceServer).GetRates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GetRatesService_GetRates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GetRatesServiceServer).GetRates(ctx, req.(*RatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GetRatesService_ServiceDesc is the grpc.ServiceDesc for GetRatesService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GetRatesService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protomodel.GetRatesService",
	HandlerType: (*GetRatesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRates",
			Handler:    _GetRatesService_GetRates_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "getrates_req.proto",
}
