// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.1
// source: getrates_req_http.proto

package protomodel

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GetRatesServiceWithHttp_GetRatesHttp_FullMethodName = "/protomodel.GetRatesServiceWithHttp/GetRatesHttp"
)

// GetRatesServiceWithHttpClient is the client API for GetRatesServiceWithHttp service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GetRatesServiceWithHttpClient interface {
	GetRatesHttp(ctx context.Context, in *RatesRequestHttp, opts ...grpc.CallOption) (*RatesResponseHttp, error)
}

type getRatesServiceWithHttpClient struct {
	cc grpc.ClientConnInterface
}

func NewGetRatesServiceWithHttpClient(cc grpc.ClientConnInterface) GetRatesServiceWithHttpClient {
	return &getRatesServiceWithHttpClient{cc}
}

func (c *getRatesServiceWithHttpClient) GetRatesHttp(ctx context.Context, in *RatesRequestHttp, opts ...grpc.CallOption) (*RatesResponseHttp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RatesResponseHttp)
	err := c.cc.Invoke(ctx, GetRatesServiceWithHttp_GetRatesHttp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetRatesServiceWithHttpServer is the server API for GetRatesServiceWithHttp service.
// All implementations must embed UnimplementedGetRatesServiceWithHttpServer
// for forward compatibility.
type GetRatesServiceWithHttpServer interface {
	GetRatesHttp(context.Context, *RatesRequestHttp) (*RatesResponseHttp, error)
	mustEmbedUnimplementedGetRatesServiceWithHttpServer()
}

// UnimplementedGetRatesServiceWithHttpServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGetRatesServiceWithHttpServer struct{}

func (UnimplementedGetRatesServiceWithHttpServer) GetRatesHttp(context.Context, *RatesRequestHttp) (*RatesResponseHttp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRatesHttp not implemented")
}
func (UnimplementedGetRatesServiceWithHttpServer) mustEmbedUnimplementedGetRatesServiceWithHttpServer() {
}
func (UnimplementedGetRatesServiceWithHttpServer) testEmbeddedByValue() {}

// UnsafeGetRatesServiceWithHttpServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GetRatesServiceWithHttpServer will
// result in compilation errors.
type UnsafeGetRatesServiceWithHttpServer interface {
	mustEmbedUnimplementedGetRatesServiceWithHttpServer()
}

func RegisterGetRatesServiceWithHttpServer(s grpc.ServiceRegistrar, srv GetRatesServiceWithHttpServer) {
	// If the following call pancis, it indicates UnimplementedGetRatesServiceWithHttpServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GetRatesServiceWithHttp_ServiceDesc, srv)
}

func _GetRatesServiceWithHttp_GetRatesHttp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RatesRequestHttp)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GetRatesServiceWithHttpServer).GetRatesHttp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GetRatesServiceWithHttp_GetRatesHttp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GetRatesServiceWithHttpServer).GetRatesHttp(ctx, req.(*RatesRequestHttp))
	}
	return interceptor(ctx, in, info, handler)
}

// GetRatesServiceWithHttp_ServiceDesc is the grpc.ServiceDesc for GetRatesServiceWithHttp service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GetRatesServiceWithHttp_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protomodel.GetRatesServiceWithHttp",
	HandlerType: (*GetRatesServiceWithHttpServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRatesHttp",
			Handler:    _GetRatesServiceWithHttp_GetRatesHttp_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "getrates_req_http.proto",
}
