// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.1
// source: getrates_req_http.proto

package protomodel

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RatesRequestHttp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RatesRequestHttp) Reset() {
	*x = RatesRequestHttp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_getrates_req_http_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RatesRequestHttp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RatesRequestHttp) ProtoMessage() {}

func (x *RatesRequestHttp) ProtoReflect() protoreflect.Message {
	mi := &file_getrates_req_http_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RatesRequestHttp.ProtoReflect.Descriptor instead.
func (*RatesRequestHttp) Descriptor() ([]byte, []int) {
	return file_getrates_req_http_proto_rawDescGZIP(), []int{0}
}

type RatesResponseHttp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rates string `protobuf:"bytes,1,opt,name=rates,proto3" json:"rates,omitempty"`
}

func (x *RatesResponseHttp) Reset() {
	*x = RatesResponseHttp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_getrates_req_http_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RatesResponseHttp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RatesResponseHttp) ProtoMessage() {}

func (x *RatesResponseHttp) ProtoReflect() protoreflect.Message {
	mi := &file_getrates_req_http_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RatesResponseHttp.ProtoReflect.Descriptor instead.
func (*RatesResponseHttp) Descriptor() ([]byte, []int) {
	return file_getrates_req_http_proto_rawDescGZIP(), []int{1}
}

func (x *RatesResponseHttp) GetRates() string {
	if x != nil {
		return x.Rates
	}
	return ""
}

var File_getrates_req_http_proto protoreflect.FileDescriptor

var file_getrates_req_http_proto_rawDesc = []byte{
	0x0a, 0x17, 0x67, 0x65, 0x74, 0x72, 0x61, 0x74, 0x65, 0x73, 0x5f, 0x72, 0x65, 0x71, 0x5f, 0x68,
	0x74, 0x74, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x22, 0x12, 0x0a, 0x10, 0x52, 0x61, 0x74, 0x65, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x74, 0x74, 0x70, 0x22, 0x29, 0x0a, 0x11, 0x52, 0x61, 0x74,
	0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x74, 0x74, 0x70, 0x12, 0x14,
	0x0a, 0x05, 0x72, 0x61, 0x74, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x72,
	0x61, 0x74, 0x65, 0x73, 0x32, 0x68, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x52, 0x61, 0x74, 0x65, 0x73,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x57, 0x69, 0x74, 0x68, 0x48, 0x74, 0x74, 0x70, 0x12,
	0x4d, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x52, 0x61, 0x74, 0x65, 0x73, 0x48, 0x74, 0x74, 0x70, 0x12,
	0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x52, 0x61, 0x74,
	0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x74, 0x74, 0x70, 0x1a, 0x1d, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x52, 0x61, 0x74, 0x65, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x74, 0x74, 0x70, 0x22, 0x00, 0x42, 0x0f,
	0x5a, 0x0d, 0x2e, 0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_getrates_req_http_proto_rawDescOnce sync.Once
	file_getrates_req_http_proto_rawDescData = file_getrates_req_http_proto_rawDesc
)

func file_getrates_req_http_proto_rawDescGZIP() []byte {
	file_getrates_req_http_proto_rawDescOnce.Do(func() {
		file_getrates_req_http_proto_rawDescData = protoimpl.X.CompressGZIP(file_getrates_req_http_proto_rawDescData)
	})
	return file_getrates_req_http_proto_rawDescData
}

var file_getrates_req_http_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_getrates_req_http_proto_goTypes = []any{
	(*RatesRequestHttp)(nil),  // 0: protomodel.RatesRequestHttp
	(*RatesResponseHttp)(nil), // 1: protomodel.RatesResponseHttp
}
var file_getrates_req_http_proto_depIdxs = []int32{
	0, // 0: protomodel.GetRatesServiceWithHttp.GetRatesHttp:input_type -> protomodel.RatesRequestHttp
	1, // 1: protomodel.GetRatesServiceWithHttp.GetRatesHttp:output_type -> protomodel.RatesResponseHttp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_getrates_req_http_proto_init() }
func file_getrates_req_http_proto_init() {
	if File_getrates_req_http_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_getrates_req_http_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*RatesRequestHttp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_getrates_req_http_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*RatesResponseHttp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_getrates_req_http_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_getrates_req_http_proto_goTypes,
		DependencyIndexes: file_getrates_req_http_proto_depIdxs,
		MessageInfos:      file_getrates_req_http_proto_msgTypes,
	}.Build()
	File_getrates_req_http_proto = out.File
	file_getrates_req_http_proto_rawDesc = nil
	file_getrates_req_http_proto_goTypes = nil
	file_getrates_req_http_proto_depIdxs = nil
}
